name: gst_billing_app
description: A GST Billing App for TATA Retail Solutions
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path: ^1.8.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # No asset references